# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Churner Prediction
tagline:          ''
description:      'Wheaton College 2022 MATH 493: Group Project' 
url:              "https://datasciencelifecycle.github.io"
baseurl:          "/math493_fall2022"


paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/datasciencelifecycle/math493_fall2022/
