# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Churn prediction
tagline:          ''
description:      'Group project of Math-493 Fall 2022' 
url:              "https://datasciencelifecycle.github.io"
baseurl:          "/math493_fall2022"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/datasciencelifecycle/math493_fall2022/
